### ISSUE TITLE
MethodInvocationException occurs randomly in Invoke-TraverseDirectoryTree adapter

### ISSUE THREAD

**Issue by plastikfan** [plastikfan/Loopz#35]
Running Xatch periodically throws errors like this:

```
_________________________________________________________________________________
   [🎶] Conversion Summary (Gatecrasher- Global Sound System (Longitude)) | ("Count" -> "17", "Skipped" -> "0", "Triggered" -> "True", "From" -> "flac", "To" -> "mp3")
_________________________________________________________________________________
   [📁] Audio Directory // ["No" => "850", "Album" => "Gatecrasher- Global Sound System (Longitude)"]
MethodInvocationException: C:\Users\Plastikfan\Documents\PowerShell\Modules\Elizium.Loopz\Elizium.Loopz.psm1:1306
Line |
1306 |      $adapted.Invoke(
     |      ~~~~~~~~~~~~~~~~
     | Exception calling "Invoke" with "5" argument(s): "Exception calling "Invoke" with "1" argument(s): "Exception calling "Invoke" with "4" argument(s): "Exception calling "Invoke" with "1" argument(s): "Exception calling
     | ".ctor" with "2" argument(s): "Count cannot be less than zero. (Parameter 'count')"""""

```

However, processing that directory by itself, does not cause the same error to be thrown. Only happens in the full batch run.

Ocurring on this line in Invoke-TraverseDirectoryTree:

```
    $adapted.Invoke(
      $_underscore,
      $_passThru['LOOPZ.TRAVERSE.CONDITION'],
      $_passThru,
      $PassThru['LOOPZ.TRAVERSE.INVOKEE'],
      $_trigger
    );
```

**Comment by plastikfan** [comment]
Found an issue here; Count was missing from the check

```powershell
      if ($passThru.ContainsKey('LOOPZ.TRAVERSE.INVOKEE.PARAMS') -and
        ($passThru['LOOPZ.TRAVERSE.INVOKEE.PARAMS'].Count -gt 0)) {
        $passThru['LOOPZ.TRAVERSE.INVOKEE.PARAMS'] | ForEach-Object {
          $positional += $_;
        }
      }
```

when re-run with this fix, found this error:

```
_________________________________________________________________________________
   [🎶] Conversion Summary (Little Fluffy Clouds (Single)) | ("Count" -> "4", "Skipped" -> "0", "Triggered" -> "True", "From" -> "flac", "To" -> "mp3")
_________________________________________________________________________________
   [📁] Audio Directory // ["No" => " 28", "Album" => "Little Fluffy Clouds (Single)"]
Invoke-ForeachFsItem: C:\Users\Plastikfan\Documents\PowerShell\Modules\Elizium.Loopz\Elizium.Loopz.psm1:1461
Line |
1461 |  …   $directoryInfos | Invoke-ForeachFsItem -Directory -Block $adapter `
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Problem with: 'E:\NVIDIA_SHIELD\Music\HI-RES\AMBIENT-TEHNO'

⨯ Plastikfan@JANUS  ~ 
```

**Comment by plastikfan** [comment]
It is not known why there are exceptions occuring here. These exceptions have no effect on the processing of the audio file batch, so they are being caught silently for lack of an alternative remediation policy.

**Comment by plastikfan** [comment]
Here is a stack trace that is displayed by writing out $_.Exception.StackTrace:

```
[+] Error: Exception calling "Invoke" with "1" argument(s): "Exception calling "Invoke" with "4" argument(s): "Exception calling "Invoke" with "1" argument(s): "Exception calling ".ctor" with "2" argument(s): "Count cannot be less than zero. (Parameter 'count')""""
[+] Trace:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
  [-] Inner Error: Exception calling "Invoke" with "1" argument(s): "Exception calling "Invoke" with "4" argument(s): "Exception calling "Invoke" with "1" argument(s): "Exception calling ".ctor" with "2" argument(s): "Count cannot be less than zero. (Parameter 'count')"""".Exception.Message
```
